### ISSUE TITLE
404 Error

### ISSUE THREAD

**Issue by hejjoe** [neue-zukunft/newsmonitor#7]
Link is broken? https://www.neuezukunft.info/wen-wir-suchen/

**Comment by hejjoe** [comment]
i guess the bug is here: https://github.com/neue-zukunft/newsmonitor/blob/main/src/App.jsx#L198

`-` /wen-wir-suchen/
`+` /mitmachen/

**Comment by noschu** [comment]
It is solved. Thank you!
